name: Docker Images

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - git_context_subdir: backend
            image_name: docker-dspace
            image_tag: 7.5
            verify_path: /usr/local/tomcat/webapps/server/index.html
            
          - git_context_subdir: frontend
            image_name: docker-dspace-angular
            image_tag: 7.5
            verify_path: /usr/src/app/dist/server/main.js
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and load docker images
        uses: docker/build-push-action@v3
        with:
          load: true
          context: "{{defaultContext}}:${{ matrix.git_context_subdir }}"
          tags: ${{ matrix.image_name }}:${{ matrix.image_tag }}

      - name: Verify docker images built success
        run: docker run --rm --entrypoint "/bin/bash" ${{ matrix.image_name }}:${{ matrix.image_tag }} -c "if [ -e ${{ matrix.verify_path }} ]; then (exit 0); else (exit 1); fi"

      - name: Build and push docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:${{ matrix.git_context_subdir }}"
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ matrix.image_tag }}, ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image_name }}:latest

